service: myfinances

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  createUser:
    handler: src/functions/CreateUser.handler
    events:
      - http:
          path: /user
          method: POST
          cors: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  dynamodb:
    stages:
      - dev
      - development
      - local
    start:
      port: 8002
      inMemory: true
      migrate: true